CREATE OR REPLACE VIEW Vista_Prenotazioni_e_Visite AS
SELECT
    P.ID_PRENOTAZIONE,
    P.CF_C AS CODICE_FISCALE_CLIENTE,
    V.DURATA_VISITA,
    V.NOME_MEDICO,
    V.TIPO_VISITA
FROM
    PRENOTAZIONE P
JOIN
    VISITA_OCULISTICA V ON P.ID_PRENOTAZIONE = V.ID_PRENOTAZIONE;

